[package]
name    = "faststorage_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow         = "1"
bitflags       = "2"
byteorder      = "1"
lz4_flex       = "0.11"
ordered-float  = "4"
